Fix build errors
Fixes the following build errors:
- src/components/admin/DemoDataGenerator.tsx(244,14): error TS2304: Cannot find name 'Settings'.
- src/components/layout/DashboardLayout.tsx(14,15): error TS2322: Type '{ userRole: "admin" | "student" | "agent"; userName: string; }' is not assignable to type 'IntrinsicAttributes'.
- src/pages/admin/EnhancedDashboard.tsx(73,33): error TS2551: Property 'getUniversitiesStats' does not exist.
- src/services/realDemoDataService.ts(232,58): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
- src/services/realDemoDataService.ts(233,63): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.